### ISSUE TITLE
when will this js lib support deboucing request?

### ISSUE THREAD

**Issue by argb** [algolia/algoliasearch-client-js#130]
Every letter a request,most times i think it's too frequent .If there's a debouce strategy I can control the request rate depends on project.

**Comment by argb** [comment]
maybe like a debouce: 300 param is needed.

**Comment by vvo** [comment]
Hi thanks for the bug report.

We left the debounce feature on the user side on purpose.

Mostly because the goal of this api client is to do http requests and that's it. It's a raw client to our API.

The debounce search is a ux challenge and not the api client scope.

It's hard to do something that will satisfy everyone, adding a debounce feature on your side is as easy as using lodash.debounce.

What do you think?

**Comment by vvo** [comment]
Hi @argb, did you have some time to read my comment? Looking forward to your thoughts

**Comment by argb** [comment]
@vvo thank you,I have read most of your document,and have integrate your service to my site,but after that I have decided to give up Algolia,case the price is very very expensive,go far beyond my affordable.
still thanks for your help.

**Comment by vvo** [comment]
Ok @argb, maybe see you in another project ! thanks for contributing here
