### ISSUE TITLE
Error on the deleteByQuery method when Distinct > 1

### ISSUE THREAD

**Issue by seafoox** [algolia/algoliasearch-client-js#134]
In the case the distinct is enabled on an index (with distinct > 1), a call to the method deleteByQuery returns the following error:

```
{
  "message": "invalid distinct value, hitsPerPage * distinct should be <= 1000",
  "status": 400
}
```

We should probably override `distinct=false` at query time when the method performs the search call.

**Comment by vvo** [comment]
If there's no issue on forcing distinct in deleteByQuery then ok.

Also I cannot remember why we limit to 1000 hits? Do we have a 1000 limit when deleting?

If the 1000 limit if for the search limit then maybe we should use browse in deleteByQuery now because browse is what we are looking for here I think
