### ISSUE TITLE
_operation on newly created objects is not triggered

### ISSUE THREAD

**Issue by mcassagnes** [algolia/algoliasearch-client-js#137]
Docs: https://www.algolia.com/doc/rest#partially-update-an-object

When partialUpdateObject creates a new object, the "_operation" is not triggered. It will however work on the second call.

Example:
```javascript
index.updatePartialObject({
  count: {
     value: 1,
    _operation: 'Increment'
  },
  objectID: "myID"
});
```
Result:
```javascript
objectID: myID
count:
 {
  "value" : 1,
  "_operation" : "Increment"
  }
```

Calling the same function again will yield the "expected" result:
```javascript
objectID: myID
count : 2
```

Is this expected behaviour? Is it possible to trigger the "_operation" on newly created objects? In the case of increments or decrements, treating undefined values as 0s.

I understand it sometimes makes no sense to add, or increment to non-existent values. However, there seem to be use cases where it does. For example: Creating a new object when it does not exist, otherwise increment its count by 1.

Kindly,
Mathieu

**Comment by vvo** [comment]
Hi @mcassagnes This is the expected behavior from our side yes, you are not experiencing a bug even if it can make sense in some situation like you said.

Maybe you could try to first .addObject() when it does not exists. https://github.com/algolia/algoliasearch-client-js#add-a-new-object-to-the-index
