### ISSUE TITLE
Compatibility with typeahead 0.11.x

### ISSUE THREAD

**Issue by chrisivens** [algolia/algoliasearch-client-js#159]
Looks like the function signature for a dataset source has changed in typeahead.

old: ` (query, cb)`
new: `(query, syncResults, asyncResults)`

Perhaps it's an ideal time to return cached results during the syncResults call if available and then the usual remote call in the async one.

**Comment by redox** [comment]
Hi @chrisivens,

yes the new typeahead release includes a lot of changes, and there are actually some bugs with remote sources... So we decided to fork it and build our own autocomplete.js library: we'll update our website to promote it in the very next days.

You shouldn't have any issue using it instead of Typeahead.js, very similar: https://github.com/algolia/autocomplete.js

Let me know if that works for you!
