### ISSUE TITLE
Missing retry in case of net::ERR

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-js#190]
It seems that the client doesn't retry in case of `net::ERR_CONNETION_TIMED_OUT` or `net::ERR_CONNECTION_REFUSED`.

You can reproduce the behavior by hacking the hosts array with something like:

```js
["appid-1.algolianet.com:1234","appid-2.algolianet.com","appid-3.algolianet.com"]
```

UPDATE: this only happens if you set a big `setRequestTimeout`.

**Comment by redox** [comment]
Also, I do a `client.setRequestTimeout(3600000);` -> maybe it explains something.

**Comment by redox** [comment]
I confirm it's because of that big `setRequestTimeout` that it fails.

**Comment by redox** [comment]
Seems like the only way to catch that with a `XMLHttpRequest` would be to do something like:

```js
      req.onreadystatechange = function() {
        if (req.readyState === 4) {
          if (req.status === 0) {
            // retry
          }
        }
      };
```

**Comment by vvo** [comment]
Just to be sure, the bug happens not just when you override the hosts array but only when you use setRequestTimeout right?

**Comment by vvo** [comment]
Here's what happens:

1. The first host is not responding, browser timeout, we get a network error.

2. Once it timeouts, it will try JSONP because we can't really now cross browser that the XHR failed because of:
- bad network
- blocked XHRS
- host not responding

3. Once JSONP also timeouts (same browser network timeout), we get a script error.

4. Now we try the second host and it works (search is triggered but it takes like 2 minutes). I also tried it with the angularjs example. It takes a fucking long time but it does works.

It takes a looooot of time (given the default browser timeouts), and that's actually why we have a low timeout on search to handle such cases (unless we say setRequestTimeout: alot).

Even if we could distinguish the network issue from other issues (as mentioned), in a cross browser way, then the error would still take a LOT of time to triggers.

What we could do is:
- distinguish the search timeout from the indexing timeout (easy)
- or use a more precise timeout by looking at the currently downloaded/uploaded data (hard, error prone maybe)

If our dashboard is really sensible to search issues then maybe just moving to a different timeout for search would be enough.

**Comment by redox** [comment]
> Just to be sure, the bug happens not just when you override the hosts array but only when you use setRequestTimeout right?

Yes, correct.

**Comment by redox** [comment]
> we can't really now cross browser

And what do you think about my `onreadystatechange` patch? Not yet sure how to deal with `XDomainRequest` but maybe we don't care :)

**Comment by vvo** [comment]
Yep the onreadystatechange only triggers after the broser timeout (verrry long)

**Comment by redox** [comment]
> distinguish the search timeout from the indexing timeout (easy): [write|search]Timeout

For sure that would help!

**Comment by vvo** [comment]
So I can introduce a non breaking change:

```js
var client = algoliasearch(appid, key, {
  timeout: {
    read: 2000
    write: 20000
  }
}); 

client.setRequestTimeout({read: 3000, write: 50000});
```

**Comment by redox** [comment]
:+1:

**Comment by vvo** [comment]
Will go in V4, #195
