### ISSUE TITLE
Bad exception name property after minification

### ISSUE THREAD

**Issue by DmitryFillo** [algolia/algoliasearch-client-js#241]
If I'll try to init algolia without ID and key, I'll recieve exception, but it's different for minified version and not.

Example for not minified version is `{name: "AlgoliaSearchError", message: "Please provide an application ID. Usage: algoliasearch(applicationID, apiKey, opts)"}`, but for minified is `{name: "o", message: "Please provide an application ID. Usage: algoliasearch(applicationID, apiKey, opts)}`. Name property is different.

It's because of [this.name = this.constructor.name](https://github.com/algolia/algoliasearch-client-js/blob/master/dist/algoliasearch.js#L4983). Also it affects any other exceptions.

I don't see any other way to get exception name. Any thoughts?

**Comment by vvo** [comment]
Hi Dimitry, can you provide a simple jsFiddle demonstrating the issue? That would help fix it. Thanks

**Comment by DmitryFillo** [comment]
https://jsfiddle.net/hejLx964/ - minified version from CDN.
https://jsfiddle.net/m703p2xz/ - non-minified version from CDN.

**Comment by vvo** [comment]
I wonder if a sourcemap would do it?

**Comment by akscheglov** [comment]
Hi, 
Seems Dmitry trying to handle exception by ex.name and cannot do it because it's changed during minification.

Also 'Function.name' is the ES6 feature and does not work for all IE (=
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

I think it's minor issue and do not waste time on this because logic on exceptions is bad practice (=

**Comment by vvo** [comment]
I just forced the default error.name to be AlgoliaSearchError, this should be sufficient to see the right name in console.

**Comment by DmitryFillo** [comment]
I think it's good enough for my case, thanks for fast reply
