### ISSUE TITLE
how to avoid umd?

### ISSUE THREAD

**Issue by acemtp** [algolia/algoliasearch-client-js#330]
We dynamically inject the algolia script with javascript using script in our client webpage.

We then access algolia with window.algoliasearch.

It works well expect if our client uses requirejs or other system in their page. In this case, algolia see there's define or require and use it. So window.algoliasearch is not available anymore.

https://jsfiddle.net/h8dghLnv/1/

Is there a way to access "algoliasearch" 100% of the time whatever the client use? The only way I found is to take the algolia code and manual hack the umd loader (first line)

**Comment by vvo** [comment]
Hi, I had a hard time having a requirejs AMD example working because I don't know much about this system of loading modules unfortunately.

Here's a live example: http://jsfiddle.net/73xVu/78/

We do not do anything exotic, we use the `--standalone algoliasearch` option of browserify which package in UMD. This is the simplest for our clients that are able to control their own environement.

If I understand well, you inject algoliasearch script in some clients webpage where you don't own the environement. So in this case the easiest would be to package your own application using browserify/webpack so you can always access the algoliasearch module no matter what.

This would be the safest bet because there are various requirejs implementation.

Would that work for you?

**Comment by acemtp** [comment]
Yes. Thanks for the feedback.
