### ISSUE TITLE
Method search shouldn't have query parameters split in two different arguments

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-client-js#50]
in v2, the signature of this method is :
`( query: String, cb: function || falsy, options: Object || falsy ) => Promise || ()`

What I'd like to have is : 
`(  params: Object || falsy, cb: function || falsy,) => Promise || ()`

**Motivation**

The changes make the api on par with the REST api. This then simplify explanations about the fact you can have the query both in arguments and in the options. This also makes complex case, with parameters for the query more straightforward.

**Cons**

Other than breaking the API compatibility, it's less straightforward for simpler cases.

**Comment by redox** [comment]
Maybe `s/parameters/params`? `parameters` disturbed me -> not sure why but I think the code I use (& write) always rather use `params`.

**Comment by bobylito** [comment]
Yes sure. Actually I do that myself. So why not :)

**Comment by vvo** [comment]
In the end I do like the `.search(query, params, cb)` because it reads: `Search this using these parameters, then callback` while `.search(params, cb) ` reads `Search using these parameters, then callback`.

We can support both very easily since the documentation [already states](https://github.com/algolia/algoliasearch-client-js#full-text-search-parameters) that we can use `query:` in params

**Comment by bobylito** [comment]
OK!
